# URLs for interacting with API
MSM_DEV_BASE_URL: 'https://dev-hpmongo.apps.pp01i.edc1.cf.ford.com/api/v1/'
CIAM_URL: "https://taas-idp-dev.auth.us-west-2.amazoncognito.com/oauth2/token"

proxy_dict: {
    'http': 'http://internet.ford.com:83',
    'https': 'http://internet.ford.com:83'
}

# File paths for .json files
input_scenario_json: 'input_data/input_scenario.json'
hash_file_path: 'hash_data/hash_lookup.json'
kpi_base_path: 'output_json/individual/'
